### ISSUE TITLE
FutureWarning: The module torch.distributed.launch is deprecated

### ISSUE THREAD

**Issue by EEElisa** [WHB139426/QA-Prompts#1]
Hi, Haibo and Weifeng! When running the training code with 'torch.distributed.launch', I encountered a FutureWarning saying that "The module torch.distributed.launch is deprecated". The appropriate alternative is to use "torchrun".

With this change, the code that references args.local_rank may need to be modified, as torchrun automatically handles this. Instead, you can extract the value of local_rank using local_rank = int(os.environ["LOCAL_RANK"]). The updated command line would be something like "CUDA_VISIBLE_DEVICES=0,1,2 torchrun --nproc_per_node=3 --master_port=1111 finetune_ans.py". 

Hope this helps!

**Comment by WHB139426** [comment]
Hi, sorry for the late response. Thanks for your advice! We will update the code to torch>=2.0 with FSDP. Thanks again!
