### ISSUE TITLE
Evaluation in finetune_ans.py

### ISSUE THREAD

**Issue by EEElisa** [WHB139426/QA-Prompts#2]
It looks like the evaluation is not supported in the main function of finetune_ans.py. Could you take a look? Thanks!

**Comment by WHB139426** [comment]
Hi EEElisa! 

1) I have modified the code so that you can validate the model during training.

2) I have also provided the trained checkpoint of  InstructBLIP-Vicuna-7B and evaluation scripts. Please refer to the README for more details.

Welcome to contact me if you have any further questions :)

**Comment by EEElisa** [comment]
Thanks so much!
